"""Add Option and fix models

Revision ID: 9502f1b8be8d
Revises: 246d49e09d9a
Create Date: 2025-05-21 15:31:54.865470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9502f1b8be8d'
down_revision: Union[str, None] = '246d49e09d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_histories_id'), 'histories', ['id'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('logic', sa.Integer(), nullable=True),
    sa.Column('empathy', sa.Integer(), nullable=True),
    sa.Column('fear', sa.Integer(), nullable=True),
    sa.Column('ambition', sa.Integer(), nullable=True),
    sa.Column('dilemma_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dilemma_id'], ['dilemmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_id'), 'options', ['id'], unique=False)
    op.drop_index('ix_history_id', table_name='history')
    op.drop_table('history')
    op.add_column('dilemmas', sa.Column('text', sa.String(), nullable=False))
    op.alter_column('dilemmas', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('dilemmas', 'question')
    op.drop_column('dilemmas', 'options')
    op.alter_column('tests', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tests', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('dilemmas', sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('dilemmas', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('dilemmas', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('dilemmas', 'text')
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name='history_test_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='history_pkey')
    )
    op.create_index('ix_history_id', 'history', ['id'], unique=False)
    op.drop_index(op.f('ix_options_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_histories_id'), table_name='histories')
    op.drop_table('histories')
    # ### end Alembic commands ###
